name: "pull request"
on: [pull_request]

jobs:
  lint_javascript:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: "lint javascript"
        run: |
          npm ci --ignore-scripts
          npm run lint:js

  jest_unit_test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: "jest unit test"
        run: |
          npm ci npm ci --ignore-scripts
          npm run test
