on:
  push:
    branches:
      - '!master'

jobs:
  lint_javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "lint javascript"
        run: |
          npm install
          npm run lint:js

  jest_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "jest unit test"
        run: |
          npm install
          npm run test
