on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - 'static/**'

jobs:
  lint_javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "lint javascript"
        run: |
          npm install
          npm run lint:js

  jest_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "jest unit test"
        run: |
          npm install
          npm run test

  build_gatsby:
    needs: [lint_javascript, jest_unit_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "builds gatsby"
        run: |
          npm install
          npm run build

  deploy_heroku:
    needs: [build_gatsby]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
